### ISSUE TITLE
améliorations

### ISSUE THREAD

**Issue by brandonsueur** [outout14/kapcss#1]
Yop,

Serait bien d'ajouter:
- Une petite documentation
- Une petite démonstration
- Un petit cdn
- Des réseaux sociaux

++

**Comment by outout14** [comment]
Okay je note

**Comment by brandonsueur** [comment]
Pas de nouvelle sur ce petit framework CSS.

**Comment by outout14** [comment]
J'ai pour le moment arrêté tous mes projets par manque de temps.
Peut être qu'un jour, je l'espère, ils reprendront ;)

**Comment by brandonsueur** [comment]
Okay nb ;)
